import React, { PropsWithChildren } from 'react'
import Header from './Header';
import Head from 'next/head';


type LayoutProps = {
  children?: React.ReactNode,
}

const Layout = ({ children }: LayoutProps) => (
  <>
   <Head>
      <title>Glocal Hack</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'></link>
    </Head>
    <Header/>
    {children}
  </>
)

export default Layout
